library_management.service:
  container_name: library_management.service
  build: ./src
  ports:
    - "5010:5010"
  environment:
    - APIPORT=5010
    - DB_HOST=${DB_HOST_LIBRARY}
    - DB_PORT=${DB_PORT_LIBRARY}
    - DB_NAME=${DB_NAME_LIBRARY}
    - DB_USER=${DB_USER_LIBRARY}
    - DB_PASSWORD=${DB_PASSWORD_LIBRARY}


library_db:
  image: mcr.microsoft.com/azure-sql-edge:latest
  container_name: library_db
  environment:
    - ACCEPT_EULA=${ACCEPT_EULA}
    - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    - MSSQL_PID=${MSSQL_PID}
  ports:
    - "1435:1433"
  networks:
    - micro-service-library
