

services:
  library_management.service:
    container_name: library_management.service
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "${APIPORT}:${APIPORT}"
    environment:
      - APIPORT=${APIPORT}
      - DBSERVER=${DBSERVER}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
    volumes:
      - ./Uploads:/app/Uploads
    networks:
      - minha-rede

  library_db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: library_db
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
